### ISSUE TITLE
Linting

### ISSUE THREAD

**Issue by ekmartin** [l12s/node-slack-client#19]
Maybe it would be a good idea to use something like [ESLint](http://eslint.org/) to make it easier for future contributors? Looking at the codebase it seems pretty similar to [Airbnb's style guide](https://github.com/airbnb/javascript/tree/master/es5) so maybe their [eslint config](https://github.com/airbnb/javascript/tree/master/packages/eslint-config-airbnb) could be a good starting point. That is, if you don't already have something else in mind.

**Comment by l12s** [comment]
Yep - this is a great idea. We have our own internal eslint configurations, which I haven't been running on this.

I'll run the linter against our code once I've got all the outstanding PRs in and get it in line with our internal standards. I'll figure out getting the eslintrc file into the repo too, pending some more comprehensive approach to making linting easier for folks.

Will close this issue once I've done the above.

**Comment by ekmartin** [comment]
Sounds great!

**Comment by l12s** [comment]
Ok, it turns out that our internal linting definitions aren't very portable for this. So I'm just going to use the AirBnB config after all: https://github.com/l12s/node-slack-client/commit/bac3df6aafd3c907b8e348d7dba94a56eb0b9e3d adds that

I'll fix the lint errors once I've merged in PRs and addressed issues so that there's no merge nightmare.
